#!/bin/sh
# summary of how this script can be called:
#        * <old-postrm> postrm remove
#        * <old-postrm> postrm purge
#        * <old-postrm> upgrade new-version
#        * <disappearer's-postrm> disappear overwriter overwriter-version
#        * <new-postrm> failed-upgrade old-version
#        * <new-postrm> abort-install
#        * <new-postrm> abort-install old-version
#        * <new-postrm> abort-upgrade old-version
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

set -e

# systemd: reload the daemon

case "$1" in
  (upgrade)
    ;;

  (purge)
    ;;

  (remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

  (*)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
